---
title: RMarkdown is the Most Powerful Codebook Maker You Can Find for Your Datasets
author: Matthew Barstead, M.S.
date: '2018-08-07'
slug: rmarkdown-is-the-most-powerful-codebook-maker-you-can-find-for-your-datasets
categories:
  - Data Visualization
tags:
  - Data Processing
  - Missing Data
  - Plotting
  - R
header:
  caption: ''
  image: ''
---

You worked hard to collect, clean, and process your data. It is finally ready for that step where you get you need to finalize your documentation. After all, it is rarely just you, the person hunched over his/her computer for the past 2 weeks learning every nook and cranny of the data, who is going to need understand and explore its contents. You can have people ask you a million and one questions. 

Or... 

You could create a manual that is complete, easy to you use, readily tweakable, completely reproducible, and 100% shareable. Having made a couple of manuals in my time as a former camp director and current Ph.D. candidate, I appreciate a well-put-together single informational resources that I can consult to quickly find the answer I want. 

By integrating R's powerful coding, graphing, and analytic abilities directly with LaTex, Rmarkdown lets you create a completely comprehensive record of everything you have done to your data (any errors can be easily tracked back to the code) while also producing an practically useful and aesthetically pleasing (at least to my eye) manual that can be shared with your research group. To see an example of its power check out an early draft of the manual I created for our current project (these data are raw, may contain as yet undiscovered inaccuracies and are not for public use). See the manual [here](https://mgb-research.netlify.com/parent_qualtrics.pdf). 